MVC/Day9/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Day9.Models;
using Day9.RepoServices;

namespace Day9.Controllers
{
    public class CoursesController : Controller
    {
        public ITraineeRepository TraineeRepo { get; }
        public ITrackRepository TrackRepo { get; }
        public ICourseRepository CourseRepo { get; }
        public TraineesDB Cont { get; }

        public CoursesController(ITraineeRepository TRepo, ITrackRepository KRepo, ICourseRepository CRepo, TraineesDB cont)
        {
            TraineeRepo = TRepo;
            TrackRepo = KRepo;
            CourseRepo = CRepo;
            Cont = cont;
        }
        private readonly TraineesDB _context;

     

        // GET: Courses
        public ActionResult Index()
        {
            return View(CourseRepo.GetAll());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int id)
        {
            if (id != null)
            {
                Course x = CourseRepo.GetDetails(id);
                if (x != null)
                    return View(x);
            }
            return RedirectToAction("Index");
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            //ViewData["TraineeID"] = new SelectList(_context.Trainees, "ID", "Birthdate");
            ViewBag.TraineeID = TraineeRepo.GetAll();
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Course course)
        {
            if (ModelState.IsValid)
            {

                CourseRepo.Insert(course);
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.TraineeID = TraineeRepo.GetAll();
            return View(CourseRepo.GetDetails(id));
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("ID,Topic,Grade,TraineeID")] Course course)
        {
            if (id != course.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    CourseRepo.UpdateCourse(id, course);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    return View();
                }
            }
            ViewData["TraineeID"] = new SelectList(_context.Trainees, "ID", "Birthdate", course.TraineeID);
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return View(CourseRepo.GetDetails(id));

          
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                CourseRepo.DeleteCourse(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.ID == id);
        }
    }
}

MVC/Day9/Controllers/TracksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Day9.Models;
using Day9.RepoServices;

namespace Day9.Controllers
{
    public class TracksController : Controller
    {
        public ITraineeRepository TraineeRepo { get; }
        public ITrackRepository TrackRepo { get; }
        public ICourseRepository CourseRepo { get; }
        public TraineesDB Cont { get; }

        public TracksController(ITraineeRepository TRepo, ITrackRepository KRepo, ICourseRepository CRepo, TraineesDB cont)
        {
            TraineeRepo = TRepo;
            TrackRepo = KRepo;
            CourseRepo = CRepo;
            Cont = cont;
        }
        private readonly TraineesDB _context;


        // GET: Tracks
        public ActionResult Index()
        {
            if(TrackRepo.GetAll() !=null)
            {
                return View(TrackRepo.GetAll());
            }
            return View();
        }

        // GET: Tracks/Details/5
        public ActionResult Details(int id)
        {
            if(id != null)
            {
                Track x = TrackRepo.GetDetails(id);
                if (x != null)
                    return View(x);
            }
            return RedirectToAction("Index");
        }

        // GET: Tracks/Create
        public ActionResult Create()
        {     
            return View();
        }

        // POST: Tracks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("ID,Name,Description")] Track track)
        {
            if (ModelState.IsValid)
            {

                TrackRepo.Insert(track);
                return RedirectToAction(nameof(Index));
            }
            return View(track);
        }

        // GET: Tracks/Edit/5
        public ActionResult Edit(int id)
        {
            return View(TrackRepo.GetDetails(id));
        }

        // POST: Tracks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, [Bind("ID,Name,Description")] Track track)
        {
            try
            {
                TrackRepo.UpdateTrack(id, track);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Tracks/Delete/5
        public ActionResult Delete(int id)
        {
            return View(TrackRepo.GetDetails(id));
        }

        // POST: Tracks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                TrackRepo.DeleteTrack(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private bool TrackExists(int id)
        {
            return _context.Tracks.Any(e => e.ID == id);
        }
    }
}

MVC/Day9/Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Day9.Models;
using Day9.RepoServices;
using Microsoft.AspNetCore.Http;

namespace Day9.Controllers
{
    public class TraineesController : Controller
    {
        public ITraineeRepository TraineeRepo { get; }
        public ITrackRepository TrackRepo { get; }
        public ICourseRepository CourseRepo { get; }
        public TraineesDB Cont { get; }

        public TraineesController(ITraineeRepository TRepo, ITrackRepository KRepo, ICourseRepository CRepo, TraineesDB cont)
        {
            TraineeRepo = TRepo;
            TrackRepo = KRepo;
            CourseRepo = CRepo;
            Cont = cont;
        }
        private readonly TraineesDB _context;

        // GET: Trainees
        public ActionResult Index()
        {
            
            return View(TraineeRepo.GetAll());
        }

        // GET: Trainees/Details/5
        public ActionResult Details(int id)
        {
            if (id != null)
            {
                Trainee x = TraineeRepo.GetDetails(id);
                if (x != null)
                    return View(x);
            }
            return RedirectToAction("Index");
        }

        // GET: Trainees/Create
        public ActionResult Create()
        {
            ViewBag.TID = TrackRepo.GetAll();
            //ViewBag.CID = CourseRepo.GetAll();
            return View();
          
        }

        // POST: Trainees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trainee trainee)
        {
            try
            {
                TraineeRepo.Insert(trainee);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Trainees/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ViewBag.TID = TrackRepo.GetAll();
            //ViewBag.CID = CourseRepo.GetAll();
            return View(TraineeRepo.GetDetails(id));
        }

        // POST: Trainees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Trainee trainee)
        {
            try
            {
                TraineeRepo.UpdateTrainee(id, trainee);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }

        }

        // GET: Trainees/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            return View(TraineeRepo.GetDetails(id));
        }

        // POST: Trainees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, IFormCollection collection)
        {
            try
            {
                TraineeRepo.DeleteTrainee(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private bool TraineeExists(int id)
        {
            return _context.Trainees.Any(e => e.ID == id);
        }
    }
}

MVC/Day9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day9</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainees" asp-action="Index">Trainees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tracks" asp-action="Index">Tracks</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
  <div class="container text-danger">
    <environment include="Development">
        <h5>
            Environment is Development
        </h5>
    </environment>

    <environment include="Staging">
        <h5>
            Environment is Staging
        </h5>
    </environment>

    <environment exclude="Development">
        <h5>
            Website is Finished...............
        </h5>
    </environment>

    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Day9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>